### ISSUE TITLE
`ActionCommandTest` fails on .net8

### ISSUE THREAD

**Issue by sky1045** [planetarium/NineChronicles.Headless#2566]
https://github.com/planetarium/NineChronicles.Headless/actions/runs/10679426371/job/29598620292

> [!NOTE]
> It should be investigated on `release/200` branch until 200 release and backmerge.

**Comment by moreal** [comment]
It is because the error message of the `byte.Parse` method becomes different since .NET 7. It can be bypassed by updating the error message assertion.

.NET 6
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/181cab5e-d9f3-4947-9d00-14031a3cb49d">

.NET 7
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/0402aff8-3401-4bbc-a8aa-2cf1c809b99b">

.NET 8
<img width="884" alt="image" src="https://github.com/user-attachments/assets/f2220a4c-e345-4241-9039-c7d19e55bd71">

**Comment by moreal** [comment]
Resolved by https://github.com/planetarium/NineChronicles.Headless/pull/2567.
