### ISSUE TITLE
[GQL] ChainQuery - BlockRef not Implemented.

### ISSUE THREAD

**Issue by FioX0** [planetarium/NineChronicles.Headless#584]
Hi Team,

Another GQL report

When doing investigations to help users identify what happened with their NCG or items, I usually run a GQL query to list a recent list of their transactions. When looking for NCG, I'd look for the hash of said transaction to then query but when running the below query:

```graphql
query{
 chainQuery{transactionQuery{transactions(desc:true signer:"0x55C00f6879Dc67b52d873A6bCd9e936BE6a81347" limit:100){id,blockRef{hash},actions{inspection}}}}
}
```

blockRef{hash} will cause the following error to show up.

```graphql
  "errors": [
    {
      "message": "This feature 'BlockRef' needsIRichStore implementation"
    },
```

**Comment by longfin** [comment]
@FioX0 Thanks for reporting. I think NineChronicles.Headless isn't ready for `blockRef` selection because it needed tx to block hash index additionally. (See also. https://github.com/planetarium/libplanet/ipull/1328, https://github.com/planetarium/libplanet/issues/1399)

- If you don't need to `blockRef`, the below query will work.

```graphql
query {
 chainQuery {
  transactionQuery {
    transactions(desc:true signer:"0x55C00f6879Dc67b52d873A6bCd9e936BE6a81347" limit:1) {
      id,
      actions {
        inspection
        }
      }
    }
  }
}

```

- if you want to use `blockRef` feature, please wait for https://github.com/planetarium/libplanet/issues/1399.
